
/**************************************************************
 *	
 *	select, 8 bit, 11025Hz,
 *	1 channel, 6615 bytes/channel
 *	Total Size: 1 * 6615 + 4 (header) = 6659 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jenny Z\Desktop\gatech school\Fall 2019\CS 2261\Final Game\M04\select.wav
 *	Time-stamp: Mon Nov 25 22:10:17 2019
 *	
 **************************************************************/

#ifndef __SELECTH__
#define __SELECTH__

#define SELECTFREQ 11025
#define SELECTLEN 6615

extern const unsigned char select[6615];

#endif /* __SELECTH__ */
