
/**************************************************************
 *	
 *	splash, 8 bit, 11025Hz,
 *	1 channel, 16141 bytes/channel
 *	Total Size: 1 * 16141 + 4 (header) = 16185 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jenny Z\Desktop\gatech school\Fall 2019\CS 2261\Final Game\M04\splash.wav
 *	Time-stamp: Wed Nov 20 16:40:40 2019
 *	
 **************************************************************/

#ifndef __SPLASHH__
#define __SPLASHH__

#define SPLASHFREQ 11025
#define SPLASHLEN 16141

extern const unsigned char splash[16141];

#endif /* __SPLASHH__ */
