
/**************************************************************
 *	
 *	toggle, 8 bit, 11025Hz,
 *	1 channel, 6086 bytes/channel
 *	Total Size: 1 * 6086 + 4 (header) = 6130 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jenny Z\Desktop\gatech school\Fall 2019\CS 2261\Final Game\M04\toggle.wav
 *	Time-stamp: Mon Nov 25 18:38:21 2019
 *	
 **************************************************************/

#ifndef __TOGGLEH__
#define __TOGGLEH__

#define TOGGLEFREQ 11025
#define TOGGLELEN 6086

extern const unsigned char toggle[6086];

#endif /* __TOGGLEH__ */
