
/**************************************************************
 *	
 *	totoroBGM, 8 bit, 11025Hz,
 *	1 channel, 1089792 bytes/channel
 *	Total Size: 1 * 1089792 + 4 (header) = 1089836 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jenny Z\Desktop\gatech school\Fall 2019\CS 2261\Final Game\M04\totoroBGM.wav
 *	Time-stamp: Wed Nov 20 15:48:16 2019
 *	
 **************************************************************/

#ifndef __TOTOROBGMH__
#define __TOTOROBGMH__

#define TOTOROBGMFREQ 11025
#define TOTOROBGMLEN 1080000

extern const unsigned char totoroBGM[1087392];

#endif /* __TOTOROBGMH__ */
